### ISSUE TITLE
Missing icon odnoklassniki

### ISSUE THREAD

**Issue by theOneV** [Grawl/Grands#23]
Отлично сделано! 
Но лично мне не хватает иконки Одноклассников. Буду рад, если в данном наборе она появится!

**Comment by theaqua** [comment]
#2 
#9 
#12 
#20 
#21 
#22

**Comment by Grawl** [comment]
Форкай и добавляй через IcoMoon, в чём проблема? Я на дух не переношу Mail.ru, они хуже, чем IE. Я написал об этом в описании проекта.
Мало того, я давно уже не занимаюсь им, перешёл на FontAwesome – там теперь есть VK, чего мне не хватало, из-за чего я и создал Grands.
